### ISSUE TITLE
Bug: Migration from inlet/react-pixi to @pixi/react

### ISSUE THREAD

**Issue by michael-motornyi** [pixijs/pixi-react#421]
### Current Behavior

After migration i am receiving an error 
![image](https://user-images.githubusercontent.com/33175499/222983950-7f4f036b-7e3c-4c94-b5fc-1bbfea0f4ee9.png)

### Expected Behavior

Pixi React should work as expected from examples

### Steps to Reproduce

Change inlet/react-pixi to @pixi/react in package json and update all imports on your project

![image](https://user-images.githubusercontent.com/33175499/222984351-5c73262b-c77b-46e6-8a79-133f704da996.png)

### Environment

Vite as bundler

"@pixi/react": "^7.0.2",
"pixi.js": "^7.1.4",
"react": "18.2.0",
"react-dom": "18.2.0",
"vite": "^4.0.3",

**Comment by baseten** [comment]
@michael-motornyi are you seeing this in an existing project or in the minimal example you've provided above? `Stage` does expect to have some `children` for example. If you're using React 18, you should also use the new `createRoot` API rather than React DOM render: https://reactjs.org/blog/2022/03/08/react-18-upgrade-guide.html#updates-to-client-rendering-apis

If neither of these work, are you able to provide a minimal reproduction on CodeSandbox and I can take a look for you
